```
/etc/doc-base/documents/README
/usr/sbin/install-docs
/usr/share/doc-base/data/doc-base.map
/usr/share/doc-base/data/section.list
/usr/share/doc-base/doc-base
/usr/share/doc-base/install-docs-man
/usr/share/doc/doc-base/changelog.gz
/usr/share/doc/doc-base/copyright
/usr/share/doc/doc-base/doc-base.html/about.html
/usr/share/doc/doc-base/doc-base.html/index.html
/usr/share/doc/doc-base/doc-base.html/informations.html
/usr/share/doc/doc-base/doc-base.html/interface.html
/usr/share/doc/doc-base/doc-base.html/todo.html
/usr/share/doc/doc-base/doc-base.txt.gz
/usr/share/doc/doc-base/doc-base.xml.gz
/usr/share/doc/doc-base/install-docs.html
/usr/share/doc/doc-base/version.ent
/usr/share/lintian/overrides/doc-base
/usr/share/locale/de/LC_MESSAGES/doc-base.mo
/usr/share/locale/es/LC_MESSAGES/doc-base.mo
/usr/share/locale/fr/LC_MESSAGES/doc-base.mo
/usr/share/locale/ja/LC_MESSAGES/doc-base.mo
/usr/share/locale/pl/LC_MESSAGES/doc-base.mo
/usr/share/locale/sv/LC_MESSAGES/doc-base.mo
/usr/share/man/de/man8/install-docs.8.gz
/usr/share/man/es/man8/install-docs.8.gz
/usr/share/man/fr/man8/install-docs.8.gz
/usr/share/man/ja/man8/install-docs.8.gz
/usr/share/man/man8/install-docs.8.gz
/usr/share/man/pl/man8/install-docs.8.gz
/usr/share/man/pt/man8/install-docs.8.gz
/usr/share/perl5/Debian/DocBase/Common.pm
/usr/share/perl5/Debian/DocBase/DB.pm
/usr/share/perl5/Debian/DocBase/DocBaseFile.pm
/usr/share/perl5/Debian/DocBase/Document.pm
/usr/share/perl5/Debian/DocBase/Gettext.pm
/usr/share/perl5/Debian/DocBase/InstallDocs.pm
/usr/share/perl5/Debian/DocBase/Programs/Dhelp.pm
/usr/share/perl5/Debian/DocBase/Programs/Dwww.pm
/usr/share/perl5/Debian/DocBase/Utils.pm


/etc/apache2/conf-available/doc-central.conf
/usr/bin/doccentral
/usr/lib/cgi-bin/doc-central/browse.cgi
/usr/lib/cgi-bin/doc-central/contents.cgi
/usr/lib/cgi-bin/doc-central/docconfig.py
/usr/lib/cgi-bin/doc-central/docinfo.py
/usr/lib/cgi-bin/doc-central/docutils.py
/usr/lib/cgi-bin/doc-central/search.cgi
/usr/lib/cgi-bin/doc-central/viewdoc.cgi
/usr/share/doc-central/www/index.html
/usr/share/doc-central/www/main.html
/usr/share/doc/doc-central/NEWS.Debian.gz
/usr/share/doc/doc-central/README
/usr/share/doc/doc-central/README.Debian
/usr/share/doc/doc-central/changelog.gz
/usr/share/doc/doc-central/copyright
/usr/share/man/man1/doccentral.1.gz
/usr/share/menu/doc-central

/usr/bin/pdb3
/usr/bin/pydoc3
/usr/bin/pygettext3
/usr/lib/valgrind/python3.supp
/usr/share/doc-base/python3.python-policy
/usr/share/doc/python3.11/python-policy.txt.gz
/usr/share/doc/python3/README.Debian
/usr/share/doc/python3/changelog.Debian.amd64.gz
/usr/share/doc/python3/changelog.Debian.gz
/usr/share/doc/python3/copyright
/usr/share/doc/python3/python-policy.txt.gz
/usr/share/lintian/overrides/python3
/usr/share/man/man1/pdb3.1.gz
/usr/share/man/man1/pydoc3.1.gz
/usr/share/man/man1/pygettext3.1.gz
/usr/share/pixmaps/python3.xpm
/usr/share/python3/python.mk
/usr/share/python3/runtime.d/public_modules.rtinstall
/usr/share/python3/runtime.d/public_modules.rtremove

/usr/bin/py3clean
/usr/bin/py3compile
/usr/bin/py3versions
/usr/bin/python3
/usr/share/doc/python3-minimal/README.Debian
/usr/share/doc/python3-minimal/changelog.Debian.amd64.gz
/usr/share/doc/python3-minimal/changelog.Debian.gz
/usr/share/doc/python3-minimal/copyright
/usr/share/man/man1/py3clean.1.gz
/usr/share/man/man1/py3compile.1.gz
/usr/share/man/man1/py3versions.1.gz
/usr/share/man/man1/python3.1.gz
/usr/share/python3/debian_defaults
/usr/share/python3/debpython/__init__.py
/usr/share/python3/debpython/files.py
/usr/share/python3/debpython/interpreter.py
/usr/share/python3/debpython/option.py
/usr/share/python3/debpython/version.py
/usr/share/python3/py3versions.py

/usr/lib/s390x-linux-gnu/libuuid.so.1
/usr/lib/s390x-linux-gnu/libuuid.so.1.3.0
/usr/share/doc/libuuid1/changelog.Debian.gz
/usr/share/doc/libuuid1/changelog.gz
/usr/share/doc/libuuid1/copyright

/usr/lib/x86_64-linux-gnu/libuuid.so.1
/usr/lib/x86_64-linux-gnu/libuuid.so.1.3.0
/usr/share/doc/libuuid1/changelog.Debian.gz
/usr/share/doc/libuuid1/changelog.gz
/usr/share/doc/libuuid1/copyright
